apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
commonLabels:
  monokle: kustomize-demo
resources:
  - nginx-demo-deployment.yaml
  - nginx-demo-service.yaml
