apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nginx-demo
  template:
    metadata:
      labels:
        deployment: nginx-demo
    spec:
      containers:
        - name: nginx-demo-container
          image: nginx:1.25.1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: nginx-demo-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
